version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    allow:
      - dependency-name: "axios"
    reviewers:
      - "alperensert"
  - package-ecosystem: "npm"
    directory: "/docs"
    schedule:
      interval: "weekly"
    ignore:
      - dependency-name: "*"
    