# Sidebar navigation

- label: "Introduction"
  link: "/"
- label: "Getting started"
  link: "/getting-started"
- label: Usage
  items:
      - label: "Image to Text"
        link: "/usage/image-to-text"
      - label: "ReCAPTCHA V2"
        link: "/usage/recaptcha-v2"
      - label: "ReCAPTCHA V2 Enterprise"
        link: "/usage/recaptcha-v2-enterprise"
      - label: "FunCaptcha"
        link: "/usage/funcaptcha"
      - label: "ReCAPTCHA V3"
        link: "/usage/recaptcha-v3"
      - label: "GeeTest"
        link: "/usage/geetest"
      - label: "Turnstile"
        link: "/usage/turnstile"
      - label: "Proxy and User Agent"
        link: "/usage/proxy-and-user-agent"
      - label: "Callback URL"
        link: "/usage/callback-url"
- label: API
  items:
      - label: class CapmonsterClient
        link: /api/capmonster-client
      - label: class CapmonsterError
        link: /api/capmonster-error
      - label: class RecaptchaV2Task
        link: /api/recaptcha-v2-task
      - label: class GeeTestTask
        link: /api/geetest-task
      - label: class ImageToTextTask
        link: /api/image-to-text-task
      - label: class RecaptchaV2EnterpriseTask
        link: /api/recaptcha-v2-enterprise-task
      - label: class RecaptchaV3Task
        link: /api/recaptcha-v3-task
      - label: class HCaptchaTask
        link: /api/hcaptcha-task
      - label: class FuncaptchaTask
        link: /api/funcaptcha-task
      - label: class TurnstileTask
        link: /api/turnstile-task
      - label: class UAProxy
        link: /api/ua-proxy-class
      - label: all interfaces
        link: /all-interfaces
- label: More
  items:
      - label: Error Types
        link: /more/error-types
      - label: No Cache
        link: /more/no-cache
      - label: "Github"
        link: https://github.com/alperensert/node-capmonster
      - label: Official Docs
        link: https://zennolab.atlassian.net/wiki/spaces/APIS/pages/491575/English+Documentation
