import type { SidebarsConfig } from "@docusaurus/plugin-content-docs"

const sidebars: SidebarsConfig = {
    gettingStartedSidebar: [{ type: "autogenerated", dirName: "." }],
}

export default sidebars
