name: Deploy docs to GitHub Pages

on:
  push:
    branches: ["master"]
    paths:
      - docs/**
  workflow_dispatch:

permissions:
  contents: write
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  publish:
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - uses: actions/checkout@v4
      - uses: retypeapp/action-build@latest
        with:
          directory: docs
      - uses: retypeapp/action-github-pages@latest
        id: deployment
        with:
          branch: gh-pages
          update-branch: true
